### ISSUE TITLE
Decide what to do about type checker failure test failure

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/dhallj#6]
The type checker acceptance test include the following failure test case:

```dhall
{ x: Natural, x: Natural }
```

We currently type check this without a failure:

```scala
scala> import org.dhallj.parser.DhallParser
import org.dhallj.parser.DhallParser

scala> DhallParser.parse("{ x: Natural, x: Natural }").typeCheck
res0: org.dhallj.core.Expr = Type
```

We could easily change the type checker to make it fail here, but [the spec seems to explicitly say](https://github.com/dhall-lang/dhall-lang/blob/a53a620df888b97fe23598356be7157bda0c8e21/standard/type-inference.md#records) that we don't need to:

> Carefully note that there should be no need to handle duplicate fields by this point because the desugaring rules for record literals merge duplicate fields into unique fields.

Right now I'm ignoring this failure test case, but I need to figure out whether I'm misunderstanding the language in the spec, and fix the type checker if I am.

**Comment by Gabriel439** [comment]
@travisbrown: I believe you will need to do something special to explicitly reject duplicate record fields in a record type.

What the spec is saying is that you don't need to do anything special to handle duplicate fields in a record *literal*, because `{ x = a, x = b }` will desugar to `{ x = a ∧ b }` and then the type-checking rules for `∧` will kick in and do the right thing.  However, there is no corresponding rule for desugaring duplicate fields in record *types*, so you just have to reject them because they are duplicates.

You might imagine that a future version of the spec might standardize that `{ x : A, x : B }` is syntactic sugar for `{ x : A //\\ B }`, but nobody's done that, yet.  However, you could imagine that if there were such a rule then `{ x : Natural, x : Natural }` would desugar to `{ x : Natural //\\ Natural }`, which would then defer to the type-checking rules for `//\\` as the reason for rejecting the duplicate field in the type.

**Comment by travisbrown** [comment]
@Gabriel439 Oh, thanks, that makes sense—I think I missed the transition from record types to record literals (maybe the "Carefully note that there should be no need to handle duplicate fields" paragraph could be moved to after the "Record values are also anonymous" one?). I'll push a fix here shortly and un-ignore the test.
